oss:
  enabled: ${OSS_ENABLED:true}
  endpoint: ${OSS_ENDPOINT:https://oss-cn-shenzhen.aliyuncs.com}
  accessKeyId: ${OSS_ACCESS_KEY_ID:your-access-key-id}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET:your-access-key-secret}
  bucketName: ${OSS_BUCKET_NAME:your-bucket-name}
  urlPrefix: ${OSS_URL_PREFIX:https://your-bucket-name.oss-cn-shenzhen.aliyuncs.com/}